# Generated by Django 5.1.1 on 2024-11-04 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Product',
        ),
    ]
