# Generated by Django 5.1.1 on 2024-11-18 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='battery',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='network',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='processor',
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='product.product'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='product.product'),
        ),
    ]
